#ifndef GFXRECON_TOOLS_OPTIMIZE_VULKAN_OPTIMIZE_OPTIONS_H
#define GFXRECON_TOOLS_OPTIMIZE_VULKAN_OPTIMIZE_OPTIONS_H

GFXRECON_BEGIN_NAMESPACE(gfxrecon)

struct VulkanOptimizationOptions
{
    bool remove_rt{ false };
};

GFXRECON_END_NAMESPACE(gfxrecon)

#endif // GFXRECON_DECODE_DX12_OPTIMIZE_OPTIONS_H
