language: cpp

sudo: false

arch:
  - amd64
  - arm64
  
compiler:
  - g++
  
install: skip

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

matrix:
  include:
    - os: linux
      arch: arm64
      addons:
        packages:
          - git
          - build-essential
          - zlib1g-dev
          - liblz4-dev
          - libzstd-dev
    - os: linux
      arch: amd64
      addons:
        packages:
          - git
          - build-essential
          - libx11-xcb-dev
          - libxcb-keysyms1-dev  
          - libwayland-dev
          - libxrandr-dev
          - zlib1g-dev
          - liblz4-dev
          - libzstd-dev
