dist: focal

jobs:
  include:
    - name: "x86 32bit linux cross-compile"
      os: linux
      arch: amd64
      language: cpp
      compiler: g++
      addons:
        apt:
          packages:
            - libx11-xcb-dev:i386
            - libxcb-keysyms1-dev:i386
            - libwayland-dev:i386
            - libxrandr-dev:i386
            - zlib1g-dev:i386
            - liblz4-dev:i386
            - libzstd-dev:i386
            - g++-multilib
      script:
        - mkdir build_x32
        - cd build_x32
        - cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/linux_x86_32.cmake
        - make
    - name: "x86 64bit linux native and arm linux cross-compiles"
      os: linux
      arch: amd64
      language: cpp
      compiler: g++
      addons:
        apt:
          packages:
            - libx11-xcb-dev
            - libxcb-keysyms1-dev
            - libwayland-dev
            - libxrandr-dev
            - zlib1g-dev
            - liblz4-dev
            - libzstd-dev
            - g++-aarch64-linux-gnu
            - g++-arm-linux-gnueabihf
      script:
        - mkdir build_x64
        - cd build_x64
        - cmake ..
        - make
        - cd ..
        - mkdir build_arm64
        - cd build_arm64
        - cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/linux_arm64.cmake
        - make
        - cd ..
        - mkdir build_arm32
        - cd build_arm32
        - cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/linux_arm.cmake
        - make
